# Cria um Usuario
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "nomeDeUsuario" : "Usuario",
    "email" : "usuario@usuario.com",
    "senha" : "123456",
    "nomeCompleto" : "Usuario de teste"
}
###
# Busca um Usuario por nomeDeUsuario
GET  http://localhost:3000/users/Usuario HTTP/1.1
Content-Type: application/json
###
# Gerando erro no campoo senha e nomecompleto
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "nomeDeUsuario" : "Usuario",
    "email" : "usuario@usuario.com"
}
###
# Retorno do erro
# {
#   "statusCode": 400,
#   "error": "Bad Request",
#   "message": [
#     {
#       "target": {
#         "nomeDeUsuario": "Usuario",
#         "email": "usuario@usuario.com"
#       },
#       "property": "senha",
#       "children": [],
#       "constraints": {
#         "isNotEmpty": "senha é obrigatório."
#       }
#     },
#     {
#       "target": {
#         "nomeDeUsuario": "Usuario",
#         "email": "usuario@usuario.com"
#       },
#       "property": "nomeCompleto",
#       "children": [],
#       "constraints": {
#         "isNotEmpty": "nomeCompleto é obrigatório."
#       }
#     }
#   ]
# }
###
# Cria um Usuario Utilizando Serialização e Interceptor
# Mudando os dados para inglês e não retornando a senha
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "userName" : "Usuario",
    "email" : "usuario@usuario.com",
    "password" : "123456",
    "fullName" : "Usuario de teste"
}
###
# {
#   "username": "Usuario",
#   "email": "usuario@usuario.com",
#   "fullname": "Usuario de teste"
# }

